from dotenv import load_dotenv  
load_dotenv()  
from langchain_groq import ChatGroq  
from langchain.agents import create_agent  
from langgraph.checkpoint.memory import InMemorySaver  
from langchain.tools import tool   
import pandas as pd  
import plotly.express as px                         # ADDED  
   
import streamlit as st  
  
_df:pd.DataFrame=None  
 
_chart_data = None                         
_chart_type = None                         
_chart_color = None                         # ADDED
 
def set_df(df:pd.DataFrame):  
    global _df  
    _df=df 
 
if "messages" not in st.session_state:  
    st.session_state.messages=[]  
if "chart_data" not in st.session_state:  
    st.session_state.chart_data = None  
  
if "chart_type" not in st.session_state:  
    st.session_state.chart_type = None  

if "chart_color" not in st.session_state:          # ADDED
    st.session_state.chart_color = None             # ADDED
 
@tool  
def get_data_info():  
    """ Get columns, datatypes, first 5 rows of uploadeed csv file """  
    if  _df is None:  
        return "No csv found"  
    return f"""  
        Shape:{_df.shape},  
        Columns & Datatype: {_df.dtypes.to_string()},  
        First five rows:{_df.head()}  
"""  
 
@tool   
def filter_tool(condition:str):  
    """ Filter rows using query condition   
    Example: age>30 and Department="Engineering"  
    """  
    if  _df is None:  
        return "No csv found"  
    try:  
        result=_df.query(condition)  
        return f"Found {len(result)} rows:{result.to_string()}"  
    except Exception as e:  
        return f"Error:{e}"  
 
@tool  
def analyze_data(expression:str):  
    """ Run pandas expression on the data-frame (referred to as df)   
    Example: df["salary"].mean()  
      
    """  
    if  _df is None:  
        return "No csv found"  
    try:  
        df = _df  
        result=eval(expression)  
        return str(result)  
    except Exception as e:  
        return f"Error:{e}"  
 
@tool  
def create_chart(expression: str, chart_type: str,color: str = ""):  
    """Create a visualization from the uploaded CSV data.  
  
    Use this tool whenever the user asks for a chart, graph,  
    plot, visualization, trend, comparison, distribution,  
    or relationship between columns.  
  
    The expression must be a valid pandas expression using df.  
  
    Supported chart types:  
    - bar  
    - line  
    - scatter  
    - pie  

    color:
    - Optional color requested by the user.
    """  
      
    if _df is None:  
        return "No csv found"  
  
    try:  
        global _chart_data, _chart_type, _chart_color       # CHANGED
 
        df = _df  
  
        # Execute the pandas expression generated by the LLM  
        result = eval(expression)  
  
        if not isinstance(result, (pd.Series, pd.DataFrame)):  
            return "Chart expression must return a pandas Series or DataFrame."  
  
        if chart_type not in ["bar", "line", "scatter", "pie"]:  
            return "Unsupported chart type. Use bar, line, scatter, or pie."  
  
        # Convert Series into DataFrame  
        if isinstance(result, pd.Series):  
            result = result.reset_index()  
         
        _chart_data = result                          
        _chart_type = chart_type   
        _chart_color = color                              # CHANGED
  
        return f"{chart_type} chart created successfully."  
  
    except Exception as e:  
        return f"Error creating chart: {e}"  
  
all_tools=[get_data_info,filter_tool,analyze_data,create_chart]  
llm=ChatGroq(model="openai/gpt-oss-120b")  
 
system_prompt = """    
You are a data analyst assistant. You help the user explore and analyze CSV data.  
  
Use the available tools to answer the user's questions.  
  
Tools:  
  
get_data_info:  
- Get the dataset shape, columns, datatypes, and first 5 rows.  
  
filter_tool:  
- Filter rows using a pandas query condition.  
  
analyze_data:  
- Run a pandas expression on the dataframe for calculations,  
  aggregations, sorting, and retrieving data.  
- The dataframe is available as `df`.  
  
create_chart:  
- Create a visualization from the uploaded CSV data.  
- Use this tool whenever the user asks for a chart, graph, plot,  
  visualization, trend, comparison, distribution, or relationship.  
- The expression must use the dataframe `df`.  
- Supported chart types are:  
  bar, line, scatter, pie.  
- If the user requests specific chart colors, you MUST pass those colors to create_chart.
- Example: if the user says "green and orange", call create_chart with color="green, orange".
- If the user does not request a color, pass color="".
  
Chart selection:  
- Use bar for categorical comparisons.  
- Use line for trends or time-series data.  
- Use scatter for relationships between two numerical variables.  
- Use pie for part-to-whole distributions.  
  
When the user explicitly asks for a visualization, ALWAYS use  
create_chart instead of only returning the calculated numbers.  
"""  
 
agent=create_agent(model=llm,tools=all_tools,checkpointer=InMemorySaver(),system_prompt=system_prompt)  
  
def run_agent(query:str):  
    res=agent.invoke(  
        {'messages':[{'role':'user','content':query}]},  
        {'configurable':{'thread_id':'1'}}  
    )  
    answer=res["messages"][-1].content  
    return answer  
 
# let's build the ui   
st.header("InsightIQ") 
st.subheader("An AI-powered data-analyst tool")
file=st.file_uploader("Select your CSV file",type="csv")  
if file:  
    df=pd.read_csv(file)  
    set_df(df)  
    st.dataframe(df.head())  
    st.success(f"Loaded {df.shape[0]} rows.")  
 
for msg in st.session_state.messages:  
    role=msg["role"]  
    content=msg["content"]  
    st.chat_message(role).markdown(content)  
 
query=st.chat_input("Ask anything...")  
 
if query:  
    st.chat_message("user").markdown(query)  
    st.session_state.messages.append({"role":"user","content":query})  
     
    res=run_agent(query)  
 
    # ADDED: transfer chart data to Streamlit after agent finishes 
    if _chart_data is not None: 
        st.session_state.chart_data = _chart_data 
        st.session_state.chart_type = _chart_type 
        st.session_state.chart_color = _chart_color             # ADDED
     
    st.chat_message("ai").markdown(res)  
    st.session_state.messages.append({"role":"ai","content":res})  
 
if st.session_state.chart_data is not None:  
  
    chart_data = st.session_state.chart_data  
    chart_type = st.session_state.chart_type  
    chart_color = st.session_state.chart_color                 # ADDED
  
    # BAR CHART  
    if chart_type == "bar": 
        colors = None
        if chart_color:
            colors = [c.strip() for c in chart_color.split(",")]  

        fig = px.bar(  
            chart_data,  
            x=chart_data.columns[0],  
            y=chart_data.columns[1],  
            color=chart_data.columns[0],
            color_discrete_sequence=colors,  
            title="Data Analysis"  
        )  

             # CHANGED
  
        st.plotly_chart(fig, use_container_width=True)  
  
  
    # LINE CHART  
    elif chart_type == "line":  
  
        fig = px.line(  
            chart_data,  
            x=chart_data.columns[0],  
            y=chart_data.columns[1],  
            markers=True,  
            title="Data Trend"  
        )  

        if chart_color:
            colors = [c.strip() for c in chart_color.split(",")]
            fig.update_traces(marker_color=colors)           # ADDED
  
        st.plotly_chart(fig, use_container_width=True)  
  
  
    # SCATTER CHART  
    elif chart_type == "scatter":  
  
        fig = px.scatter(  
            chart_data,  
            x=chart_data.columns[0],  
            y=chart_data.columns[1],  
            title="Data Relationship"  
        )  

        if chart_color:
            colors = [c.strip() for c in chart_color.split(",")]
            fig.update_traces(marker_color=colors)         # ADDED
  
        st.plotly_chart(fig, use_container_width=True)  
  
  
    # PIE CHART  
    elif chart_type == "pie":  
  
        fig = px.pie(  
            chart_data,  
            names=chart_data.columns[0],  
            values=chart_data.columns[1],  
            title="Data Distribution"  
        )  

        if chart_color:
            colors = [c.strip() for c in chart_color.split(",")]
            fig.update_traces(marker_colors=colors)     # ADDED
  
        st.plotly_chart(fig, use_container_width=True)